### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ethanfree23** [learn-co-curriculum/phase-1-callback-functions#1]
### Canvas Link

https://learning.flatironschool.com/courses/4557/pages/callback-functions?module_item_id=335559

### Concern

link at bottom resource should be https://javascriptissexy.com/tag/callback-functions/

**Comment by lizbur10** [comment]
Hi @ethanfree23 ! Thanks for flagging this! 

The current link seems to be working now - there may have just been a temporary problem with the site - so I'm going to go ahead and close this issue. If you are still unable to access the link, feel free to reopen it.

Thanks for contributing to the Flatiron School curriculum 💙
