### ISSUE TITLE
'Callback Functions' Lesson Needs Reference To 'Higher Order' Function

### ISSUE THREAD

**Issue by SamuelBanya** [learn-co-curriculum/phase-1-callback-functions#2]
### Canvas Link

https://learning.flatironschool.com/courses/5284/pages/callback-functions?module_item_id=375577

### Concern

The 'Callback Functions' lesson should have a reference to 'Higher Order' function and include the same 'Resources' section as the 'First-Class Functions' lesson.

This is necessary because a later lab, this one in particular, requires the student to have known this:
https://learning.flatironschool.com/courses/5284/assignments/172154?module_item_id=375584

Only on a separate lesson, "First-Class Functions" is this mentioned but only in the "Resources" section:
https://learning.flatironschool.com/courses/5284/assignments/172084?module_item_id=375581

This is the specific article mentioned:
https://javascriptissexy.com/understand-javascript-callback-functions-and-use-them/#more-1037

**Comment by AlveeM** [comment]
Hi @SamuelBanya, thank you for submitting this issue.

We've updated the lesson resource and added a "Higher-Order Function" section in the "First-Class Functions" lab. The changes may not immediately appear on your Canvas instance. Please check the linked GitHub repo to see the updated text until the changes are synced.

Thanks again for submitting the issue and helping us improve the curriculum!
